words = [
    "algumas",
    "altera",
    "ama",
    "amizade",
    "amizades",
    "apenas",
    "aprendi",
    "busca",
    "cenas",
    "chata",
    "cofused",
    "comunidade",
    "configurar",
    "crescimento",
    "criada",
    "cubo",
    "código",
    "dar",
    "das",
    "dela",
    "dentre",
    "devido",
    "dia",
    "diferenças",
    "diz",
    "ela",
    "elas",
    "elemento",
    "emana",
    "especiais",
    "espiritual",
    "essa",
    "essas",
    "evitar",
    "exclusiva",
    "exclusivamente",
    "exclusivo",
    "explicar",
    "extrapolação",
    "família",
    "fazem",
    "fim",
    "foi",
    "gabrielly",
    "ganhar",
    "gosto",
    "grande",
    "ideias",
    "iferentes<",
    "importa",
    "impossível",
    "iniciar",
    "invejável",
    "já",
    "lgbtqia",
    "louvável",
    "lá",
    "mais",
    "maturidade",
    "mbti",
    "mensagens",
    "milhões",
    "mostradas",
    "muito",
    "média",
    "nascem",
    "ntre",
    "não",
    "nós",
    "obtem",
    "paciente",
    'pecia",',
    "personalidade",
    "pessoa",
    "pode",
    "por",
    "possível",
    "página",
    "quem",
    "realmente",
    "reflete",
    "relacionamento",
    "revelar",
    "sabe",
    "sensatas",
    "serem",
    "serão",
    "sincera",
    "sobre",
    "somos",
    "sua",
    "suas",
    "talvez",
    "tela",
    "tem",
    "terminaram",
    "titlefrontfront",
    "todas",
    "uma",
    "usar",
    "vem",
    "você",
]
